# Generated by Django 4.2 on 2024-11-03 12:08

import Product.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=255)),
                ('ad_url', models.FileField(blank=True, null=True, upload_to='AD/ad_url/<function AD_directory at 0x0000020DC6EEB880>')),
                ('image', models.FileField(blank=True, null=True, upload_to='AD/image/<function AD_directory at 0x0000020DC6EEB880>')),
                ('video', models.FileField(blank=True, null=True, upload_to='AD/ad_videos/<function AD_directory at 0x0000020DC6EEB880>')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone_Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=12, verbose_name='PassWord')),
                ('image', models.FileField(blank=True, default='default.png', null=True, upload_to='CustomUser/image')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('last_version_number', models.IntegerField(default=1)),
                ('do_update_now', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('electricity_consumption', models.FloatField(default=0)),
                ('image_url', models.FileField(blank=True, max_length=200, null=True, upload_to=Product.models.product_directory)),
                ('last_version_number', models.IntegerField(default=1)),
                ('last_version_url', models.FileField(blank=True, max_length=200, null=True, upload_to='Product/version_url/<function product_directory at 0x0000020DC6EE3920>')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='State', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Action', to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Room', max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voice_Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, unique=True)),
                ('action_state', models.IntegerField(default=0)),
                ('command', models.CharField(max_length=250)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item_Voice_Command', to='Product.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version_number', models.IntegerField(default=1)),
                ('last_version_url', models.FileField(blank=True, max_length=200, null=True, upload_to='Update/version_url/<function update_directory at 0x0000020DC6EE94E0>')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Update', to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Items', to='Product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Room_Item', to='Product.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='item',
            name='users_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_Item', to='Product.customuser', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customer_Complaint', to='Product.customuser', verbose_name='Customer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item_Complaint', to='Product.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Action',
            fields=[
                ('product_action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product_action')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Action', to='Product.item', verbose_name='Item')),
            ],
            bases=('Product.product_action',),
        ),
    ]
