# Generated by Django 4.2 on 2024-10-28 15:39

import Product.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=255)),
                ('ad_url', models.FileField(blank=True, null=True, upload_to='AD/ad_url/<function AD_directory at 0x00000205D88FC9A0>')),
                ('image', models.FileField(blank=True, null=True, upload_to='AD/image/<function AD_directory at 0x00000205D88FC9A0>')),
                ('video', models.FileField(blank=True, null=True, upload_to='AD/ad_videos/<function AD_directory at 0x00000205D88FC9A0>')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('image', models.FileField(blank=True, default='default.png', null=True, upload_to='CustomUser/image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_mac_ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('last_version', models.IntegerField(default=1)),
                ('do_update_now', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('electricity_consumption', models.FloatField(default=0)),
                ('image_url', models.FileField(blank=True, max_length=200, null=True, upload_to=Product.models.product_directory)),
                ('last_version_number', models.IntegerField(default=1)),
                ('last_version_url', models.FileField(blank=True, max_length=200, null=True, upload_to='Product/version_url/<function product_directory at 0x00000205D88D32E0>')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voice_Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, unique=True)),
                ('action_state', models.IntegerField(default=0)),
                ('command', models.CharField(max_length=250)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item_Voice_Command', to='Product.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version_number', models.IntegerField(default=1)),
                ('last_version_url', models.FileField(blank=True, max_length=200, null=True, upload_to='Update/version_url/<function update_directory at 0x00000205D88D3100>')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Update', to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(related_name='Product_Items', to='Product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Room_Item', to='Product.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='item',
            name='users_list',
            field=models.ManyToManyField(related_name='used_item', to='Product.customuser'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customer_Complaint', to='Product.customuser', verbose_name='Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item_Complaint', to='Product.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='switch_state', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item_Action', to='Product.item', verbose_name='Item')),
            ],
        ),
    ]
