# Generated by Django 4.2 on 2024-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_remove_room_slug_alter_ad_ad_url_alter_ad_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="item",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AlterField(
            model_name="ad",
            name="ad_url",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="AD/ad_url/<function AD_directory at 0x77a5a59bd120>",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="AD/image/<function AD_directory at 0x77a5a59bd120>",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="AD/ad_videos/<function AD_directory at 0x77a5a59bd120>",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_version_url",
            field=models.FileField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="Product/version_url/<function product_directory at 0x77a5a59be4d0>",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="last_version_url",
            field=models.FileField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="Update/version_url/<function update_directory at 0x77a5a59bf250>",
            ),
        ),
    ]
