# Generated by Django 4.2 on 2024-10-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_ad_ad_url_alter_ad_image_alter_ad_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_url',
            field=models.FileField(blank=True, null=True, upload_to='AD/ad_url/<function AD_directory at 0x000001F120CB2DE0>'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='AD/image/<function AD_directory at 0x000001F120CB2DE0>'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='AD/ad_videos/<function AD_directory at 0x000001F120CB2DE0>'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='products',
        ),
        migrations.RemoveField(
            model_name='item',
            name='users_list',
        ),
        migrations.AlterField(
            model_name='product',
            name='last_version_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Product/version_url/<function product_directory at 0x000001F120CB3240>'),
        ),
        migrations.AlterField(
            model_name='update',
            name='last_version_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Update/version_url/<function update_directory at 0x000001F120CB2B60>'),
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='Product_Items', to='Product.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='users_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='User_Item', to='Product.customuser', verbose_name='User'),
            preserve_default=False,
        ),
    ]
