# Generated by Django 4.2 on 2024-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_ad_ad_url_alter_ad_image_alter_ad_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='', max_length=12, verbose_name='PassWord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_url',
            field=models.FileField(blank=True, null=True, upload_to='AD/ad_url/<function AD_directory at 0x0000020D3EE9CA40>'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='AD/image/<function AD_directory at 0x0000020D3EE9CA40>'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='AD/ad_videos/<function AD_directory at 0x0000020D3EE9CA40>'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Phone_Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_version_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Product/version_url/<function product_directory at 0x0000020D3EE73060>'),
        ),
        migrations.AlterField(
            model_name='update',
            name='last_version_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Update/version_url/<function update_directory at 0x0000020D3EE72D40>'),
        ),
    ]
