# Generated by Django 4.2 on 2024-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_ad_ad_url_alter_ad_image_alter_ad_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_url',
            field=models.FileField(blank=True, null=True, upload_to='AD/ad_url/<function AD_directory at 0x00000229B9897880>'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='AD/image/<function AD_directory at 0x00000229B9897880>'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='AD/ad_videos/<function AD_directory at 0x00000229B9897880>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_version_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Product/version_url/<function product_directory at 0x00000229B9895F80>'),
        ),
        migrations.AlterField(
            model_name='update',
            name='last_version_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Update/version_url/<function update_directory at 0x00000229B98954E0>'),
        ),
    ]
