# Generated by Django 4.2 on 2024-11-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Brand"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "BRAND",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Color"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "COLOR",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Customer"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, unique=True, verbose_name="Phone"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CUSTOMER",
            },
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="MainCategory"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MAIN_CAT",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Supplier"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, unique=True, verbose_name="Phone"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SUPPLIER",
            },
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="UOM"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UOM",
            },
        ),
        migrations.CreateModel(
            name="WHSBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Branch"),
                ),
                ("detail", models.CharField(max_length=200, verbose_name="Detail")),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "WHS_Branch",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="SubCategory"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
                (
                    "main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="MainCategory",
                        to="CONF.maincategory",
                        verbose_name="Main",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SUP_CAT",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Note"
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="SubCategory",
                        to="CONF.subcategory",
                        verbose_name="SubCategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CATEGORY",
            },
        ),
    ]
